site_name: prefect-ascii-brightcove-vimeo
repo_url: https://github.com/myohei/prefect-ascii-brightcove-vimeo
theme:
  name: material
  palette:
    primary: blue
    accent: blue
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            show_signature: False
            heading_level: 1
      watch:
        - prefect_ascii_brightcove_vimeo/
        - README.md

nav:
    - Home: index.md
    - Tasks: tasks.md
    - Flows: flows.md

